import 'package:flutter/material.dart';
import 'package:nrmcontrolapp/Shared/Icons/flutter_icon_model.dart';

import '../Colors/icons_colors.dart';

class FlutterIcons {
  static Widget getPasswordIcon(isPassword) {
    return Icon(isPassword ? Icons.remove_red_eye : Icons.lock_open_outlined,
        color: IconsColors.stringTextFieldIconColor);
  }

  static Widget getLockerIcon() {
    return const Icon(Icons.lock, color: IconsColors.stringTextFieldIconColor);
  }

  static Icon peopleIcon = const Icon(Icons.people);
  static Icon searchIcon = const Icon(Icons.search);
  static String familyPackage = 'MaterialIcons';

  static List<FlutterIconModel> iconList = <FlutterIconModel>[
    FlutterIconModel(Icons.abc, "abc"),
    FlutterIconModel(Icons.abc_outlined, "abc"),
    FlutterIconModel(Icons.abc_rounded, "abc"),
    FlutterIconModel(Icons.abc_sharp, "abc_sharp"),
    FlutterIconModel(Icons.ac_unit, "ac_unit"),
    FlutterIconModel(Icons.ac_unit_outlined, "ac_unit_outlined"),
    FlutterIconModel(Icons.ac_unit_sharp, "ac_unit_sharp"),
    FlutterIconModel(Icons.access_alarm, "access_alarm"),
    FlutterIconModel(Icons.access_alarm_outlined, "access_alarm_outlined"),
    FlutterIconModel(Icons.access_alarm_sharp, "access_alarm_sharp"),
    FlutterIconModel(Icons.access_alarms, "access_alarms"),
    FlutterIconModel(Icons.access_alarms_outlined, "access_alarms_outlined"),
    FlutterIconModel(Icons.access_alarms_sharp, "access_alarms_sharp"),
    FlutterIconModel(Icons.access_time, "access_time"),
    FlutterIconModel(Icons.access_time_filled, "access_time_filled"),
    FlutterIconModel(
        Icons.access_time_filled_outlined, "access_time_filled_outlined"),
    FlutterIconModel(
        Icons.access_time_filled_rounded, "access_time_filled_rounded"),
    FlutterIconModel(
        Icons.access_time_filled_sharp, "access_time_filled_sharp"),
    FlutterIconModel(Icons.access_time_outlined, "access_time_outlined"),
    FlutterIconModel(Icons.access_time_rounded, "access_time_rounded"),
    FlutterIconModel(Icons.access_time_sharp, "access_time_sharp"),
    FlutterIconModel(Icons.accessibility, "accessibility"),
    FlutterIconModel(Icons.accessibility_new, "accessibility_new"),
    FlutterIconModel(
        Icons.accessibility_new_outlined, "accessibility_new_outlined"),
    FlutterIconModel(
        Icons.accessibility_new_rounded, "accessibility_new_rounded"),
    FlutterIconModel(Icons.accessibility_new_sharp, "accessibility_new_sharp"),
    FlutterIconModel(Icons.accessibility_outlined, "accessibility_outlined"),
    FlutterIconModel(Icons.accessibility_rounded, "accessibility_rounded"),
    FlutterIconModel(Icons.accessible, "accessible"),
    FlutterIconModel(Icons.accessible_forward, "accessible_forward"),
    FlutterIconModel(
        Icons.accessible_forward_outlined, "accessible_forward_outlined"),
    FlutterIconModel(
        Icons.accessible_forward_rounded, "accessible_forward_rounded"),
    FlutterIconModel(
        Icons.accessible_forward_sharp, "accessible_forward_sharp"),
    FlutterIconModel(Icons.accessible_outlined, "accessible_outlined"),
    FlutterIconModel(Icons.accessible_rounded, "accessible_rounded"),
    FlutterIconModel(Icons.accessible_sharp, "accessible_sharp"),
    FlutterIconModel(Icons.account_balance, "account_balance"),
    FlutterIconModel(
        Icons.account_balance_outlined, "account_balance_outlined"),
    FlutterIconModel(Icons.account_balance_rounded, "account_balance_rounded"),
    FlutterIconModel(Icons.account_balance_sharp, "account_balance_sharp"),
    FlutterIconModel(Icons.account_balance_wallet, "account_balance_wallet"),
    FlutterIconModel(Icons.account_balance_wallet_outlined,
        "account_balance_wallet_outlined"),
    FlutterIconModel(
        Icons.account_balance_wallet_rounded, "account_balance_wallet_rounded"),
    FlutterIconModel(
        Icons.account_balance_wallet_sharp, "account_balance_wallet_sharp"),
    FlutterIconModel(Icons.account_box, "account_box"),
    FlutterIconModel(Icons.account_box_outlined, "account_box_outlined"),
    FlutterIconModel(Icons.account_box_rounded, "account_box_rounded"),
    FlutterIconModel(Icons.account_box_sharp, "account_box_sharp"),
    FlutterIconModel(Icons.account_circle, "account_circle"),
    FlutterIconModel(Icons.account_circle_outlined, "account_circle_outlined"),
    FlutterIconModel(Icons.account_circle_rounded, "account_circle_rounded"),
    FlutterIconModel(Icons.account_circle_sharp, "account_circle_sharp"),
    FlutterIconModel(Icons.account_tree, "account_tree"),
    FlutterIconModel(Icons.account_tree_outlined, "account_tree_outlined"),
    FlutterIconModel(Icons.account_tree_rounded, "account_tree_rounded"),
    FlutterIconModel(Icons.account_tree_sharp, "account_tree_sharp"),
    FlutterIconModel(Icons.ad_units, "ad_units"),
    FlutterIconModel(Icons.ad_units_outlined, "ad_units_outlined"),
    FlutterIconModel(Icons.ad_units_rounded, "ad_units_rounded"),
    FlutterIconModel(Icons.ad_units_sharp, "ad_units_sharp"),
    FlutterIconModel(Icons.add, "add"),
    FlutterIconModel(Icons.add_a_photo, "add_a_photo"),
    FlutterIconModel(Icons.add_a_photo_outlined, "add_a_photo_outlined"),
    FlutterIconModel(Icons.add_a_photo_rounded, "add_a_photo_rounded"),
    FlutterIconModel(Icons.add_a_photo_sharp, "add_a_photo_sharp"),
    FlutterIconModel(Icons.add_alarm, "add_alarm"),
    FlutterIconModel(Icons.add_alarm_outlined, "add_alarm_outlined"),
    FlutterIconModel(Icons.add_alarm_rounded, "add_alarm_rounded"),
    FlutterIconModel(Icons.add_alarm_sharp, "add_alarm_sharp"),
    FlutterIconModel(Icons.add_alert, "add_alert"),
    FlutterIconModel(Icons.add_alert_outlined, "add_alert_outlined"),
    FlutterIconModel(Icons.add_alert_rounded, "add_alert_rounded"),
    FlutterIconModel(Icons.add_alert_sharp, "add_alert_sharp"),
    FlutterIconModel(Icons.add_box, "add_box"),
    FlutterIconModel(Icons.add_box_outlined, "add_box_outlined"),
    FlutterIconModel(Icons.add_box_rounded, "add_box_rounded"),
    FlutterIconModel(Icons.add_box_sharp, "add_box_sharp"),
    FlutterIconModel(Icons.add_business, "add_business"),
    FlutterIconModel(Icons.add_business_outlined, "add_business_outlined"),
    FlutterIconModel(Icons.add_business_rounded, "add_business_rounded"),
    FlutterIconModel(Icons.add_business_sharp, "add_business_sharp"),
    FlutterIconModel(Icons.add_call, "add_call"),
    FlutterIconModel(Icons.add_card, "add_card"),
    FlutterIconModel(Icons.add_card_outlined, "add_card_outlined"),
    FlutterIconModel(Icons.add_card_rounded, "add_card_rounded"),
    FlutterIconModel(Icons.add_card_sharp, "add_card_sharp"),
    FlutterIconModel(Icons.add_chart, "add_chart"),
    FlutterIconModel(Icons.add_chart_outlined, "add_chart_outlined"),
    FlutterIconModel(Icons.add_chart_rounded, "add_chart_rounded"),
    FlutterIconModel(Icons.add_chart_sharp, "add_chart_sharp"),
    FlutterIconModel(Icons.add_circle, "add_circle"),
    FlutterIconModel(Icons.add_circle_outline, "add_circle_outline"),
    FlutterIconModel(
        Icons.add_circle_outline_outlined, "add_circle_outline_outlined"),
    FlutterIconModel(
        Icons.add_circle_outline_rounded, "add_circle_outline_rounded"),
    FlutterIconModel(
        Icons.add_circle_outline_sharp, "add_circle_outline_sharp"),
    FlutterIconModel(Icons.add_circle_outlined, "add_circle_outlined"),
    FlutterIconModel(Icons.add_circle_rounded, "add_circle_rounded"),
    FlutterIconModel(Icons.add_circle_sharp, "add_circle_sharp"),
    FlutterIconModel(Icons.add_comment, "add_comment"),
    FlutterIconModel(Icons.add_comment_outlined, "add_comment_outlined"),
    FlutterIconModel(Icons.add_comment_rounded, "add_comment_rounded"),
    FlutterIconModel(Icons.add_comment_sharp, "add_comment_sharp"),
    FlutterIconModel(Icons.add_home, "add_home"),
    FlutterIconModel(Icons.add_home_outlined, "add_home_outlined"),
    FlutterIconModel(Icons.add_home_rounded, "add_home_rounded"),
    FlutterIconModel(Icons.add_home_sharp, "add_home_sharp"),
    FlutterIconModel(Icons.add_home_work, "add_home_work"),
    FlutterIconModel(Icons.add_home_work_outlined, "add_home_work_outlined"),
    FlutterIconModel(Icons.add_home_work_rounded, "add_home_work_rounded"),
    FlutterIconModel(Icons.add_home_work_sharp, "add_home_work_sharp"),
    FlutterIconModel(Icons.add_ic_call, "add_ic_call"),
    FlutterIconModel(Icons.add_ic_call_outlined, "add_ic_call_outlined"),
    FlutterIconModel(Icons.add_ic_call_rounded, "add_ic_call_rounded"),
    FlutterIconModel(Icons.add_ic_call_sharp, "add_ic_call_sharp"),
    FlutterIconModel(Icons.add_link, "add_link"),
    FlutterIconModel(Icons.add_link_outlined, "add_link_outlined"),
    FlutterIconModel(Icons.add_link_rounded, "add_link_rounded"),
    FlutterIconModel(Icons.add_link_sharp, "add_link_sharp"),
    FlutterIconModel(Icons.add_location, "add_location"),
    FlutterIconModel(Icons.add_location_alt, "add_location_alt"),
    FlutterIconModel(
        Icons.add_location_alt_outlined, "add_location_alt_outlined"),
    FlutterIconModel(
        Icons.add_location_alt_rounded, "add_location_alt_rounded"),
    FlutterIconModel(Icons.add_location_alt_sharp, "add_location_alt_sharp"),
    FlutterIconModel(Icons.add_location_outlined, "add_location_outlined"),
    FlutterIconModel(Icons.add_location_rounded, "add_location_rounded"),
    FlutterIconModel(Icons.add_location_sharp, "add_location_sharp"),
    FlutterIconModel(Icons.add_moderator, "add_moderator"),
    FlutterIconModel(Icons.add_moderator_outlined, "add_moderator_outlined"),
    FlutterIconModel(Icons.add_moderator_rounded, "add_moderator_rounded"),
    FlutterIconModel(Icons.add_moderator_sharp, "add_moderator_sharp"),
    FlutterIconModel(Icons.add_outlined, "add_outlined"),
    FlutterIconModel(Icons.add_photo_alternate, "add_photo_alternate"),
    FlutterIconModel(
        Icons.add_photo_alternate_outlined, "add_photo_alternate_outlined"),
    FlutterIconModel(
        Icons.add_photo_alternate_rounded, "add_photo_alternate_rounded"),
    FlutterIconModel(
        Icons.add_photo_alternate_sharp, "add_photo_alternate_sharp"),
    FlutterIconModel(Icons.add_reaction, "add_reaction"),
    FlutterIconModel(Icons.add_reaction_outlined, "add_reaction_outlined"),
    FlutterIconModel(Icons.add_reaction_rounded, "add_reaction_rounded"),
    FlutterIconModel(Icons.add_reaction_sharp, "add_reaction_sharp"),
    FlutterIconModel(Icons.add_road, "add_road"),
    FlutterIconModel(Icons.add_road_outlined, "add_road_outlined"),
    FlutterIconModel(Icons.add_road_rounded, "add_road_rounded"),
    FlutterIconModel(Icons.add_road_sharp, "add_road_sharp"),
    FlutterIconModel(Icons.add_rounded, "add_rounded"),
    FlutterIconModel(Icons.add_sharp, "add_sharp"),
    FlutterIconModel(Icons.add_shopping_cart, "add_shopping_cart"),
    FlutterIconModel(
        Icons.add_shopping_cart_outlined, "add_shopping_cart_outlined"),
    FlutterIconModel(
        Icons.add_shopping_cart_rounded, "add_shopping_cart_rounded"),
    FlutterIconModel(Icons.add_shopping_cart_sharp, "add_shopping_cart_sharp"),
    FlutterIconModel(Icons.add_task, "add_task"),
    FlutterIconModel(Icons.add_task_outlined, "add_task_outlined"),
    FlutterIconModel(Icons.add_task_rounded, "add_task_rounded"),
    FlutterIconModel(Icons.add_task_sharp, "add_task_sharp"),
    FlutterIconModel(Icons.add_to_drive, "add_to_drive"),
    FlutterIconModel(Icons.add_to_drive_outlined, "add_to_drive_outlined"),
    FlutterIconModel(Icons.add_to_drive_rounded, "add_to_drive_rounded"),
    FlutterIconModel(Icons.add_to_drive_sharp, "add_to_drive_sharp"),
    FlutterIconModel(Icons.add_to_home_screen, "add_to_home_screen"),
    FlutterIconModel(
        Icons.add_to_home_screen_outlined, "add_to_home_screen_outlined"),
    FlutterIconModel(
        Icons.add_to_home_screen_rounded, "add_to_home_screen_rounded"),
    FlutterIconModel(
        Icons.add_to_home_screen_sharp, "add_to_home_screen_sharp"),
    FlutterIconModel(Icons.add_to_photos, "add_to_photos"),
    FlutterIconModel(Icons.add_to_photos_outlined, "add_to_photos_outlined"),
    FlutterIconModel(Icons.add_to_photos_rounded, "add_to_photos_rounded"),
    FlutterIconModel(Icons.add_to_photos_sharp, "add_to_photos_sharp"),
    FlutterIconModel(Icons.add_to_queue, "add_to_queue"),
    FlutterIconModel(Icons.add_to_queue_outlined, "add_to_queue_outlined"),
    FlutterIconModel(Icons.add_to_queue_rounded, "add_to_queue_rounded"),
    FlutterIconModel(Icons.add_to_queue_sharp, "add_to_queue_sharp"),
    FlutterIconModel(Icons.addchart, "addchart"),
    FlutterIconModel(Icons.addchart_outlined, "addchart_outlined"),
    FlutterIconModel(Icons.addchart_rounded, "addchart_rounded"),
    FlutterIconModel(Icons.addchart_sharp, "addchart_sharp"),
    FlutterIconModel(Icons.adf_scanner, "adf_scanner"),
    FlutterIconModel(Icons.adf_scanner_outlined, "adf_scanner_outlined"),
    FlutterIconModel(Icons.adf_scanner_rounded, "adf_scanner_rounded"),
    FlutterIconModel(Icons.adf_scanner_sharp, "adf_scanner_sharp"),
    FlutterIconModel(Icons.adjust, "adjust"),
    FlutterIconModel(Icons.adjust_outlined, "adjust_outlined"),
    FlutterIconModel(Icons.adjust_rounded, "adjust_rounded"),
    FlutterIconModel(Icons.adjust_sharp, "adjust_sharp"),
    FlutterIconModel(Icons.admin_panel_settings, "admin_panel_settings"),
    FlutterIconModel(
        Icons.admin_panel_settings_outlined, "admin_panel_settings_outlined"),
    FlutterIconModel(
        Icons.admin_panel_settings_rounded, "admin_panel_settings_rounded"),
    FlutterIconModel(
        Icons.admin_panel_settings_sharp, "admin_panel_settings_sharp"),
    FlutterIconModel(Icons.adobe, "adobe"),
    FlutterIconModel(Icons.adobe_outlined, "adobe_outlined"),
    FlutterIconModel(Icons.adobe_rounded, "adobe_rounded"),
    FlutterIconModel(Icons.adobe_sharp, "adobe_sharp"),
    FlutterIconModel(Icons.ads_click, "ads_click"),
    FlutterIconModel(Icons.ads_click_outlined, "ads_click_outlined"),
    FlutterIconModel(Icons.ads_click_rounded, "ads_click_rounded"),
    FlutterIconModel(Icons.ads_click_sharp, "ads_click_sharp"),
    FlutterIconModel(Icons.agriculture, "agriculture"),
    FlutterIconModel(Icons.agriculture_outlined, "agriculture_outlined"),
    FlutterIconModel(Icons.agriculture_rounded, "agriculture_rounded"),
    FlutterIconModel(Icons.agriculture_sharp, "agriculture_sharp"),
    FlutterIconModel(Icons.air, "air"),
    FlutterIconModel(Icons.air_outlined, "air_outlined"),
    FlutterIconModel(Icons.air_rounded, "air_rounded"),
    FlutterIconModel(Icons.air_sharp, "air_sharp"),
    FlutterIconModel(Icons.airline_seat_flat, "airline_seat_flat"),
    FlutterIconModel(
        Icons.airline_seat_flat_angled, "airline_seat_flat_angled"),
    FlutterIconModel(Icons.airline_seat_flat_angled_outlined,
        "airline_seat_flat_angled_outlined"),
    FlutterIconModel(Icons.airline_seat_flat_angled_rounded,
        "airline_seat_flat_angled_rounded"),
    FlutterIconModel(
        Icons.airline_seat_flat_angled_sharp, "airline_seat_flat_angled_sharp"),
    FlutterIconModel(
        Icons.airline_seat_flat_outlined, "airline_seat_flat_outlined"),
    FlutterIconModel(
        Icons.airline_seat_flat_rounded, "airline_seat_flat_rounded"),
    FlutterIconModel(Icons.airline_seat_flat_sharp, "airline_seat_flat_sharp"),
    FlutterIconModel(
        Icons.airline_seat_individual_suite, "airline_seat_individual_suite"),
    FlutterIconModel(Icons.airline_seat_individual_suite_outlined,
        "airline_seat_individual_suite_outlined"),
    FlutterIconModel(Icons.airline_seat_individual_suite_rounded,
        "airline_seat_individual_suite_rounded"),
    FlutterIconModel(Icons.airline_seat_individual_suite_sharp,
        "airline_seat_individual_suite_sharp"),
    FlutterIconModel(
        Icons.airline_seat_legroom_extra, "airline_seat_legroom_extra"),
    FlutterIconModel(Icons.airline_seat_legroom_extra_outlined,
        "airline_seat_legroom_extra_outlined"),
    FlutterIconModel(Icons.airline_seat_legroom_extra_rounded,
        "airline_seat_legroom_extra_rounded"),
    FlutterIconModel(Icons.airline_seat_legroom_extra_sharp,
        "airline_seat_legroom_extra_sharp"),
    FlutterIconModel(
        Icons.airline_seat_legroom_normal, "airline_seat_legroom_normal"),
    FlutterIconModel(Icons.airline_seat_legroom_normal_outlined,
        "airline_seat_legroom_normal_outlined"),
    FlutterIconModel(Icons.airline_seat_legroom_normal_rounded,
        "airline_seat_legroom_normal_rounded"),
    FlutterIconModel(Icons.airline_seat_legroom_normal_sharp,
        "airline_seat_legroom_normal_sharp"),
    FlutterIconModel(
        Icons.airline_seat_legroom_reduced, "airline_seat_legroom_reduced"),
    FlutterIconModel(Icons.airline_seat_legroom_reduced_outlined,
        "airline_seat_legroom_reduced_outlined"),
    FlutterIconModel(Icons.airline_seat_legroom_reduced_rounded,
        "airline_seat_legroom_reduced_rounded"),
    FlutterIconModel(Icons.airline_seat_legroom_reduced_sharp,
        "airline_seat_legroom_reduced_sharp"),
    FlutterIconModel(
        Icons.airline_seat_recline_extra, "airline_seat_recline_extra"),
    FlutterIconModel(Icons.airline_seat_recline_extra_outlined,
        "airline_seat_recline_extra_outlined"),
    FlutterIconModel(Icons.airline_seat_recline_extra_rounded,
        "airline_seat_recline_extra_rounded"),
    FlutterIconModel(Icons.airline_seat_recline_extra_sharp,
        "airline_seat_recline_extra_sharp"),
    FlutterIconModel(
        Icons.airline_seat_recline_normal, "airline_seat_recline_normal"),
    FlutterIconModel(Icons.airline_seat_recline_normal_rounded,
        "airline_seat_recline_normal_rounded"),
    FlutterIconModel(Icons.airline_seat_recline_normal_outlined,
        "airline_seat_recline_normal_outlined"),
    FlutterIconModel(Icons.airline_seat_recline_normal_sharp,
        "airline_seat_recline_normal_sharp"),
    FlutterIconModel(Icons.airline_stops, "airline_stops"),
    FlutterIconModel(Icons.airline_stops_outlined, "airline_stops_outlined"),
    FlutterIconModel(Icons.airline_stops_rounded, "airline_stops_rounded"),
    FlutterIconModel(Icons.airline_stops_sharp, "airline_stops_sharp"),
    FlutterIconModel(Icons.airlines, "airlines"),
    FlutterIconModel(Icons.airlines_outlined, "airlines_outlined"),
    FlutterIconModel(Icons.airlines_rounded, "airlines_rounded"),
    FlutterIconModel(Icons.airlines_sharp, "airlines_sharp"),
    FlutterIconModel(Icons.airplane_ticket, "airplane_ticket"),
    FlutterIconModel(
        Icons.airplane_ticket_outlined, "airplane_ticket_outlined"),
    FlutterIconModel(Icons.airplane_ticket_rounded, "airplane_ticket_rounded"),
    FlutterIconModel(Icons.airplane_ticket_sharp, "airplane_ticket_sharp"),
    FlutterIconModel(Icons.airplanemode_active, "airplanemode_active"),
    FlutterIconModel(
        Icons.airplanemode_active_outlined, "airplanemode_active_outlined"),
    FlutterIconModel(
        Icons.airplanemode_active_rounded, "airplanemode_active_rounded"),
    FlutterIconModel(
        Icons.airplanemode_active_sharp, "airplanemode_active_sharp"),
    FlutterIconModel(Icons.airplanemode_inactive, "airplanemode_inactive"),
    FlutterIconModel(
        Icons.airplanemode_inactive_outlined, "airplanemode_inactive_outlined"),
    FlutterIconModel(
        Icons.airplanemode_inactive_rounded, "airplanemode_inactive_rounded"),
    FlutterIconModel(
        Icons.airplanemode_inactive_sharp, "airplanemode_inactive_sharp"),
    FlutterIconModel(Icons.airplanemode_off, "airplanemode_off"),
    FlutterIconModel(
        Icons.airplanemode_off_outlined, "airplanemode_off_outlined"),
    FlutterIconModel(
        Icons.airplanemode_off_rounded, "airplanemode_off_rounded"),
    FlutterIconModel(Icons.airplanemode_off_sharp, "airplanemode_off_sharp"),
    FlutterIconModel(Icons.airplanemode_on, "airplanemode_on"),
    FlutterIconModel(
        Icons.airplanemode_on_outlined, "airplanemode_on_outlined"),
    FlutterIconModel(Icons.airplanemode_on_rounded, "airplanemode_on_rounded"),
    FlutterIconModel(Icons.airplanemode_on_sharp, "airplanemode_on_sharp"),
    FlutterIconModel(Icons.airplay, "airplay"),
    FlutterIconModel(Icons.airplay_outlined, "airplay_outlined"),
    FlutterIconModel(Icons.airplay_rounded, "airplay_rounded"),
    FlutterIconModel(Icons.airplay_sharp, "airplay_sharp"),
    FlutterIconModel(Icons.airport_shuttle, "airport_shuttle"),
    FlutterIconModel(
        Icons.airport_shuttle_outlined, "airport_shuttle_outlined"),
    FlutterIconModel(Icons.airport_shuttle_rounded, "airport_shuttle_rounded"),
    FlutterIconModel(Icons.airport_shuttle_sharp, "airport_shuttle_sharp"),
    FlutterIconModel(Icons.alarm, "alarm"),
    FlutterIconModel(Icons.alarm_add, "alarm_add"),
    FlutterIconModel(Icons.alarm_add_outlined, "alarm_add_outlined"),
    FlutterIconModel(Icons.alarm_add_rounded, "alarm_add_rounded"),
    FlutterIconModel(Icons.alarm_add_sharp, "alarm_add_sharp"),
    FlutterIconModel(Icons.alarm_off, "alarm_off"),
    FlutterIconModel(Icons.alarm_off_outlined, "alarm_off_outlined"),
    FlutterIconModel(Icons.alarm_off_rounded, "alarm_off_rounded"),
    FlutterIconModel(Icons.alarm_off_sharp, "alarm_off_sharp"),
    FlutterIconModel(Icons.alarm_on, "alarm_on"),
    FlutterIconModel(Icons.alarm_on_outlined, "alarm_on_outlined"),
    FlutterIconModel(Icons.alarm_on_rounded, "alarm_on_rounded"),
    FlutterIconModel(Icons.alarm_on_sharp, "alarm_on_sharp"),
    FlutterIconModel(Icons.alarm_outlined, "alarm_outlined"),
    FlutterIconModel(Icons.alarm_rounded, "alarm_rounded"),
    FlutterIconModel(Icons.alarm_sharp, "alarm_sharp"),
    FlutterIconModel(Icons.album, "album"),
    FlutterIconModel(Icons.album_outlined, "album_outlined"),
    FlutterIconModel(Icons.album_rounded, "album_rounded"),
    FlutterIconModel(Icons.album_sharp, "album_sharp"),
    FlutterIconModel(Icons.align_horizontal_center, "align_horizontal_center"),
    FlutterIconModel(Icons.align_horizontal_center_outlined,
        "align_horizontal_center_outlined"),
    FlutterIconModel(Icons.align_horizontal_center_rounded,
        "align_horizontal_center_rounded"),
    FlutterIconModel(
        Icons.align_horizontal_center_sharp, "align_horizontal_center_sharp"),
    FlutterIconModel(Icons.align_horizontal_left, "align_horizontal_left"),
    FlutterIconModel(
        Icons.align_horizontal_left_outlined, "align_horizontal_left_outlined"),
    FlutterIconModel(
        Icons.align_horizontal_left_rounded, "align_horizontal_left_rounded"),
    FlutterIconModel(
        Icons.align_horizontal_left_sharp, "align_horizontal_left_sharp"),
    FlutterIconModel(Icons.align_horizontal_right, "align_horizontal_right"),
    FlutterIconModel(Icons.align_horizontal_right_outlined,
        "align_horizontal_right_outlined"),
    FlutterIconModel(
        Icons.align_horizontal_right_rounded, "align_horizontal_right_rounded"),
    FlutterIconModel(
        Icons.align_horizontal_right_sharp, "align_horizontal_right_sharp"),
    FlutterIconModel(Icons.align_vertical_center, "align_vertical_center"),
    FlutterIconModel(
        Icons.align_vertical_center_outlined, "align_vertical_center_outlined"),
    FlutterIconModel(
        Icons.align_vertical_center_rounded, "align_vertical_center_rounded"),
    FlutterIconModel(
        Icons.align_vertical_center_sharp, "align_vertical_center_sharp"),
    FlutterIconModel(Icons.align_vertical_bottom, "align_vertical_bottom"),
    FlutterIconModel(
        Icons.align_vertical_bottom_outlined, "align_vertical_bottom_outlined"),
    FlutterIconModel(
        Icons.align_vertical_bottom_rounded, "align_vertical_bottom_rounded"),
    FlutterIconModel(
        Icons.align_vertical_bottom_sharp, "align_vertical_bottom_sharp"),
    FlutterIconModel(Icons.align_vertical_center, "align_vertical_center"),
    FlutterIconModel(
        Icons.align_vertical_center_outlined, "align_vertical_center_outlined"),
    FlutterIconModel(
        Icons.align_vertical_center_rounded, "align_vertical_center_rounded"),
    FlutterIconModel(
        Icons.align_vertical_center_sharp, "align_vertical_center_sharp"),
    FlutterIconModel(Icons.all_inbox, "all_inbox"),
    FlutterIconModel(Icons.all_inbox_outlined, "all_inbox_outlined"),
    FlutterIconModel(Icons.all_inbox_rounded, "all_inbox_rounded"),
    FlutterIconModel(Icons.all_inbox_sharp, "all_inbox_sharp"),
    FlutterIconModel(Icons.all_inclusive, "all_inclusive"),
    FlutterIconModel(Icons.all_inclusive_outlined, "all_inclusive_outlined"),
    FlutterIconModel(Icons.all_inclusive_rounded, "all_inclusive_rounded"),
    FlutterIconModel(Icons.all_inclusive_sharp, "all_inclusive_sharp"),
    FlutterIconModel(Icons.all_out, "all_out"),
    FlutterIconModel(Icons.all_out_outlined, "all_out_outlined"),
    FlutterIconModel(Icons.all_out_rounded, "all_out_rounded"),
    FlutterIconModel(Icons.all_out_sharp, "all_out_sharp"),
    FlutterIconModel(Icons.alt_route, "alt_route"),
    FlutterIconModel(Icons.alt_route_outlined, "alt_route_outlined"),
    FlutterIconModel(Icons.alt_route_rounded, "alt_route_rounded"),
    FlutterIconModel(Icons.alt_route_sharp, "alt_route_sharp"),
    FlutterIconModel(Icons.alternate_email, "alternate_email"),
    FlutterIconModel(
        Icons.alternate_email_outlined, "alternate_email_outlined"),
    FlutterIconModel(Icons.alternate_email_rounded, "alternate_email_rounded"),
    FlutterIconModel(Icons.alternate_email_sharp, "alternate_email_sharp"),
    FlutterIconModel(Icons.amp_stories, "amp_stories"),
    FlutterIconModel(Icons.amp_stories_outlined, "amp_stories_outlined"),
    FlutterIconModel(Icons.amp_stories_rounded, "amp_stories_rounded"),
    FlutterIconModel(Icons.amp_stories_sharp, "amp_stories_sharp"),
    FlutterIconModel(Icons.analytics, "analytics"),
    FlutterIconModel(Icons.analytics_outlined, "analytics_outlined"),
    FlutterIconModel(Icons.analytics_rounded, "analytics_rounded"),
    FlutterIconModel(Icons.analytics_sharp, "analytics_sharp"),
    FlutterIconModel(Icons.anchor, "anchor"),
    FlutterIconModel(Icons.anchor_rounded, "anchor_rounded"),
    FlutterIconModel(Icons.anchor_outlined, "anchor_outlined"),
    FlutterIconModel(Icons.anchor_sharp, "anchor_sharp"),
    FlutterIconModel(Icons.android, "android"),
    FlutterIconModel(Icons.android_outlined, "android_outlined"),
    FlutterIconModel(Icons.android_rounded, "android_rounded"),
    FlutterIconModel(Icons.android_sharp, "android_sharp"),
    FlutterIconModel(Icons.animation, "animation"),
    FlutterIconModel(Icons.animation_outlined, "animation_outlined"),
    FlutterIconModel(Icons.animation_rounded, "animation_rounded"),
    FlutterIconModel(Icons.animation_sharp, "animation_sharp"),
    FlutterIconModel(Icons.announcement, "announcement"),
    FlutterIconModel(Icons.announcement_outlined, "announcement_outlined"),
    FlutterIconModel(Icons.announcement_rounded, "announcement_rounded"),
    FlutterIconModel(Icons.announcement_sharp, "announcement_sharp"),
    FlutterIconModel(Icons.aod, "aod"),
    FlutterIconModel(Icons.aod_outlined, "aod_outlined"),
    FlutterIconModel(Icons.aod_rounded, "aod_rounded"),
    FlutterIconModel(Icons.aod_sharp, "aod_sharp"),
    FlutterIconModel(Icons.apartment, "apartment"),
    FlutterIconModel(Icons.apartment_outlined, "apartment_outlined"),
    FlutterIconModel(Icons.apartment_rounded, "apartment_rounded"),
    FlutterIconModel(Icons.apartment_sharp, "apartment_sharp"),
    FlutterIconModel(Icons.api, "api"),
    FlutterIconModel(Icons.api_outlined, "api_outlined"),
    FlutterIconModel(Icons.api_rounded, "api_rounded"),
    FlutterIconModel(Icons.api_sharp, "api_sharp"),
    FlutterIconModel(Icons.app_blocking, "app_blocking"),
    FlutterIconModel(Icons.app_blocking_outlined, "app_blocking_outlined"),
    FlutterIconModel(Icons.app_blocking_rounded, "app_blocking_rounded"),
    FlutterIconModel(Icons.app_blocking_sharp, "app_blocking_sharp"),
    FlutterIconModel(Icons.app_registration, "app_registration"),
    FlutterIconModel(
        Icons.app_registration_outlined, "app_registration_outlined"),
    FlutterIconModel(
        Icons.app_registration_rounded, "app_registration_rounded"),
    FlutterIconModel(Icons.app_registration_sharp, "app_registration_sharp"),
    FlutterIconModel(Icons.app_settings_alt, "app_settings_alt"),
    FlutterIconModel(
        Icons.app_settings_alt_outlined, "app_settings_alt_outlined"),
    FlutterIconModel(
        Icons.app_settings_alt_rounded, "app_settings_alt_rounded"),
    FlutterIconModel(Icons.app_settings_alt_sharp, "app_settings_alt_sharp"),
    FlutterIconModel(Icons.app_shortcut, "app_shortcut"),
    FlutterIconModel(Icons.app_shortcut_rounded, "app_shortcut_rounded"),
    FlutterIconModel(Icons.app_shortcut_outlined, "app_shortcut_outlined"),
    FlutterIconModel(Icons.app_shortcut_sharp, "app_shortcut_sharp"),
    FlutterIconModel(Icons.apple, "apple"),
    FlutterIconModel(Icons.apple_outlined, "apple_outlined"),
    FlutterIconModel(Icons.apple_rounded, "apple_rounded"),
    FlutterIconModel(Icons.apple_sharp, "apple_sharp"),
    FlutterIconModel(Icons.approval, "approval"),
    FlutterIconModel(Icons.approval_outlined, "approval_outlined"),
    FlutterIconModel(Icons.approval_rounded, "approval_rounded"),
    FlutterIconModel(Icons.approval_sharp, "approval_sharp"),
    FlutterIconModel(Icons.apps, "apps"),
    FlutterIconModel(Icons.apps_outage, "apps_outage"),
    FlutterIconModel(Icons.apps_outage_outlined, "apps_outage_outlined"),
    FlutterIconModel(Icons.apps_outage_rounded, "apps_outage_rounded"),
    FlutterIconModel(Icons.apps_outage_sharp, "apps_outage_sharp"),
    FlutterIconModel(Icons.apps_outlined, "apps_outlined"),
    FlutterIconModel(Icons.apps_rounded, "apps_rounded"),
    FlutterIconModel(Icons.apps_sharp, "apps_sharp"),
    FlutterIconModel(Icons.architecture, "architecture"),
    FlutterIconModel(Icons.architecture_outlined, "architecture_outlined"),
    FlutterIconModel(Icons.architecture_rounded, "architecture_rounded"),
    FlutterIconModel(Icons.architecture_sharp, "architecture_sharp"),
    FlutterIconModel(Icons.archive, "archive"),
    FlutterIconModel(Icons.archive_rounded, "archive_rounded"),
    FlutterIconModel(Icons.archive_outlined, "archive_outlined"),
    FlutterIconModel(Icons.archive_sharp, "archive_sharp"),
    FlutterIconModel(Icons.area_chart, "area_chart"),
    FlutterIconModel(Icons.area_chart_outlined, "area_chart_outlined"),
    FlutterIconModel(Icons.area_chart_rounded, "area_chart_rounded"),
    FlutterIconModel(Icons.area_chart_sharp, "area_chart_sharp"),
    FlutterIconModel(Icons.arrow_back, "arrow_back"),
    FlutterIconModel(Icons.arrow_back_ios, "arrow_back_ios"),
    FlutterIconModel(Icons.arrow_back_ios_new, "arrow_back_ios_new"),
    FlutterIconModel(
        Icons.arrow_back_ios_new_outlined, "arrow_back_ios_new_outlined"),
    FlutterIconModel(
        Icons.arrow_back_ios_new_rounded, "arrow_back_ios_new_rounded"),
    FlutterIconModel(
        Icons.arrow_back_ios_new_sharp, "arrow_back_ios_new_sharp"),
    FlutterIconModel(Icons.arrow_back_ios_outlined, "arrow_back_ios_outlined"),
    FlutterIconModel(Icons.arrow_back_ios_rounded, "arrow_back_ios_rounded"),
    FlutterIconModel(Icons.arrow_back_ios_sharp, "arrow_back_ios_sharp"),
    FlutterIconModel(Icons.arrow_back_outlined, "arrow_back_outlined"),
    FlutterIconModel(Icons.arrow_back_rounded, "arrow_back_rounded"),
    FlutterIconModel(Icons.arrow_back_sharp, "arrow_back_sharp"),
    FlutterIconModel(Icons.arrow_circle_down, "arrow_circle_down"),
    FlutterIconModel(
        Icons.arrow_circle_down_outlined, "arrow_circle_down_outlined"),
    FlutterIconModel(
        Icons.arrow_circle_down_rounded, "arrow_circle_down_rounded"),
    FlutterIconModel(Icons.arrow_circle_down_sharp, "arrow_circle_down_sharp"),
    FlutterIconModel(Icons.arrow_circle_left, "arrow_circle_left"),
    FlutterIconModel(
        Icons.arrow_circle_left_outlined, "arrow_circle_left_outlined"),
    FlutterIconModel(
        Icons.arrow_circle_left_rounded, "arrow_circle_left_rounded"),
    FlutterIconModel(Icons.arrow_circle_left_sharp, "arrow_circle_left_sharp"),
    FlutterIconModel(Icons.arrow_circle_right, "arrow_circle_right"),
    FlutterIconModel(
        Icons.arrow_circle_right_outlined, "arrow_circle_right_outlined"),
    FlutterIconModel(
        Icons.arrow_circle_right_rounded, "arrow_circle_right_rounded"),
    FlutterIconModel(
        Icons.arrow_circle_right_sharp, "arrow_circle_right_sharp"),
    FlutterIconModel(Icons.arrow_circle_up, "arrow_circle_up"),
    FlutterIconModel(
        Icons.arrow_circle_up_outlined, "arrow_circle_up_outlined"),
    FlutterIconModel(Icons.arrow_circle_up_rounded, "arrow_circle_up_rounded"),
    FlutterIconModel(Icons.arrow_circle_up_sharp, "arrow_circle_up_sharp"),
    FlutterIconModel(Icons.arrow_downward, "arrow_downward"),
    FlutterIconModel(Icons.arrow_downward_outlined, "arrow_downward_outlined"),
    FlutterIconModel(Icons.arrow_downward_rounded, "arrow_downward_rounded"),
    FlutterIconModel(Icons.arrow_downward_sharp, "arrow_downward_sharp"),
    FlutterIconModel(Icons.arrow_drop_down, "arrow_drop_down"),
    FlutterIconModel(Icons.arrow_drop_down_circle, "arrow_drop_down_circle"),
    FlutterIconModel(Icons.arrow_drop_down_circle_outlined,
        "arrow_drop_down_circle_outlined"),
    FlutterIconModel(
        Icons.arrow_drop_down_circle_rounded, "arrow_drop_down_circle_rounded"),
    FlutterIconModel(
        Icons.arrow_drop_down_circle_sharp, "arrow_drop_down_circle_sharp"),
    FlutterIconModel(
        Icons.arrow_drop_down_outlined, "arrow_drop_down_outlined"),
    FlutterIconModel(Icons.arrow_drop_down_rounded, "arrow_drop_down_rounded"),
    FlutterIconModel(Icons.arrow_drop_down_sharp, "arrow_drop_down_sharp"),
    FlutterIconModel(Icons.arrow_drop_up, "arrow_drop_up"),
    FlutterIconModel(Icons.arrow_drop_up_outlined, "arrow_drop_up_outlined"),
    FlutterIconModel(Icons.arrow_drop_up_rounded, "arrow_drop_up_rounded"),
    FlutterIconModel(Icons.arrow_drop_up_sharp, "arrow_drop_up_sharp"),
    FlutterIconModel(Icons.arrow_forward, "arrow_forward"),
    FlutterIconModel(Icons.arrow_forward_ios, "arrow_forward_ios"),
    FlutterIconModel(
        Icons.arrow_forward_ios_outlined, "arrow_forward_ios_outlined"),
    FlutterIconModel(
        Icons.arrow_forward_ios_rounded, "arrow_forward_ios_rounded"),
    FlutterIconModel(Icons.arrow_forward_ios_sharp, "arrow_forward_ios_sharp"),
    FlutterIconModel(Icons.arrow_forward_outlined, "arrow_forward_outlined"),
    FlutterIconModel(Icons.arrow_forward_rounded, "arrow_forward_rounded"),
    FlutterIconModel(Icons.arrow_forward_sharp, "arrow_forward_sharp"),
    FlutterIconModel(Icons.arrow_left, "arrow_left"),
    FlutterIconModel(Icons.arrow_left_outlined, "arrow_left_outlined"),
    FlutterIconModel(Icons.arrow_left_rounded, "arrow_left_rounded"),
    FlutterIconModel(Icons.arrow_left_sharp, "arrow_left_sharp"),
    FlutterIconModel(Icons.arrow_right, "arrow_right"),
    FlutterIconModel(Icons.arrow_right_alt, "arrow_right_alt"),
    FlutterIconModel(
        Icons.arrow_right_alt_outlined, "arrow_right_alt_outlined"),
    FlutterIconModel(Icons.arrow_right_alt_rounded, "arrow_right_alt_rounded"),
    FlutterIconModel(Icons.arrow_right_alt_sharp, "arrow_right_alt_sharp"),
    FlutterIconModel(Icons.arrow_right_outlined, "arrow_right_outlined"),
    FlutterIconModel(Icons.arrow_right_rounded, "arrow_right_rounded"),
    FlutterIconModel(Icons.arrow_right_sharp, "arrow_right_sharp"),
    FlutterIconModel(Icons.arrow_upward, "arrow_upward"),
    FlutterIconModel(Icons.arrow_upward_outlined, "arrow_upward_outlined"),
    FlutterIconModel(Icons.arrow_upward_rounded, "arrow_upward_rounded"),
    FlutterIconModel(Icons.arrow_upward_sharp, "arrow_upward_sharp"),
    FlutterIconModel(Icons.art_track, "art_track"),
    FlutterIconModel(Icons.art_track_outlined, "art_track_outlined"),
    FlutterIconModel(Icons.art_track_rounded, "art_track_rounded"),
    FlutterIconModel(Icons.art_track_sharp, "art_track_sharp"),
    FlutterIconModel(Icons.article, "article"),
    FlutterIconModel(Icons.article_outlined, "article_outlined"),
    FlutterIconModel(Icons.article_rounded, "article_rounded"),
    FlutterIconModel(Icons.article_sharp, "article_sharp"),
    FlutterIconModel(Icons.aspect_ratio, "aspect_ratio"),
    FlutterIconModel(Icons.aspect_ratio_outlined, "aspect_ratio_outlined"),
    FlutterIconModel(Icons.aspect_ratio_rounded, "aspect_ratio_rounded"),
    FlutterIconModel(Icons.aspect_ratio_sharp, "aspect_ratio_sharp"),
    FlutterIconModel(Icons.assessment, "assessment"),
    FlutterIconModel(Icons.assessment_outlined, "assessment_outlined"),
    FlutterIconModel(Icons.assessment_rounded, "assessment_rounded"),
    FlutterIconModel(Icons.assessment_sharp, "assessment_sharp"),
    FlutterIconModel(Icons.assignment, "assignment"),
    FlutterIconModel(Icons.assignment_ind, "assignment_ind"),
    FlutterIconModel(Icons.assignment_ind_outlined, "assignment_ind_outlined"),
    FlutterIconModel(Icons.assignment_ind_sharp, "assignment_ind_sharp"),
    FlutterIconModel(Icons.assignment_late, "assignment_late"),
    FlutterIconModel(
        Icons.assignment_late_outlined, "assignment_late_outlined"),
    FlutterIconModel(Icons.assignment_late_rounded, "assignment_late_rounded"),
    FlutterIconModel(Icons.assignment_late_sharp, "assignment_late_sharp"),
    FlutterIconModel(Icons.assignment_outlined, "assignment_outlined"),
    FlutterIconModel(Icons.assignment_return, "assignment_return"),
    FlutterIconModel(
        Icons.assignment_return_outlined, "assignment_return_outlined"),
    FlutterIconModel(
        Icons.assignment_return_rounded, "assignment_return_rounded"),
    FlutterIconModel(Icons.assignment_return_sharp, "assignment_return_sharp"),
    FlutterIconModel(Icons.assignment_returned, "assignment_returned"),
    FlutterIconModel(
        Icons.assignment_returned_outlined, "assignment_returned_outlined"),
    FlutterIconModel(
        Icons.assignment_returned_rounded, "assignment_returned_rounded"),
    FlutterIconModel(
        Icons.assignment_returned_sharp, "assignment_returned_sharp"),
    FlutterIconModel(Icons.assignment_rounded, "assignment_rounded"),
    FlutterIconModel(Icons.assignment_sharp, "assignment_sharp"),
    FlutterIconModel(Icons.assignment_turned_in, "assignment_turned_in"),
    FlutterIconModel(
        Icons.assignment_turned_in_outlined, "assignment_turned_in_outlined"),
    FlutterIconModel(
        Icons.assignment_turned_in_rounded, "assignment_turned_in_rounded"),
    FlutterIconModel(
        Icons.assignment_turned_in_sharp, "assignment_turned_in_sharp"),
    FlutterIconModel(Icons.assistant, "assistant"),
    FlutterIconModel(Icons.assistant_direction, "assistant_direction"),
    FlutterIconModel(
        Icons.assistant_direction_outlined, "assistant_direction_outlined"),
    FlutterIconModel(
        Icons.assistant_direction_rounded, "assistant_direction_rounded"),
    FlutterIconModel(
        Icons.assistant_direction_sharp, "assistant_direction_sharp"),
    FlutterIconModel(Icons.assistant_navigation, "assistant_navigation"),
    FlutterIconModel(Icons.assistant_outlined, "assistant_outlined"),
    FlutterIconModel(Icons.assistant_photo, "assistant_photo"),
    FlutterIconModel(
        Icons.assistant_photo_outlined, "assistant_photo_outlined"),
    FlutterIconModel(Icons.assistant_photo_rounded, "assistant_photo_rounded"),
    FlutterIconModel(Icons.assistant_photo_sharp, "assistant_photo_sharp"),
    FlutterIconModel(Icons.assistant_rounded, "assistant_rounded"),
    FlutterIconModel(Icons.assistant_sharp, "assistant_sharp"),
    FlutterIconModel(Icons.assured_workload, "assured_workload"),
    FlutterIconModel(
        Icons.assured_workload_outlined, "assured_workload_outlined"),
    FlutterIconModel(
        Icons.assured_workload_rounded, "assured_workload_rounded"),
    FlutterIconModel(Icons.assured_workload_sharp, "assured_workload_sharp"),
    FlutterIconModel(Icons.atm, "atm"),
    FlutterIconModel(Icons.atm_outlined, "atm_outlined"),
    FlutterIconModel(Icons.atm_rounded, "atm_rounded"),
    FlutterIconModel(Icons.atm_sharp, "atm_sharp"),
    FlutterIconModel(Icons.attach_email, "attach_email"),
    FlutterIconModel(Icons.attach_email_outlined, "attach_email_outlined"),
    FlutterIconModel(Icons.attach_email_rounded, "attach_email_rounded"),
    FlutterIconModel(Icons.attach_email_sharp, "attach_email_sharp"),
    FlutterIconModel(Icons.attach_file, "attach_file"),
    FlutterIconModel(Icons.attach_file_rounded, "attach_file_rounded"),
    FlutterIconModel(Icons.attach_file_outlined, "attach_file_outlined"),
    FlutterIconModel(Icons.attach_file_sharp, "attach_file_sharp"),
    FlutterIconModel(Icons.attach_money, "attach_money"),
    FlutterIconModel(Icons.attach_money_outlined, "attach_money_outlined"),
    FlutterIconModel(Icons.attach_money_rounded, "attach_money_rounded"),
    FlutterIconModel(Icons.attach_money_sharp, "attach_money_sharp"),
    FlutterIconModel(Icons.attachment, "attachment"),
    FlutterIconModel(Icons.attachment_outlined, "attachment_outlined"),
    FlutterIconModel(Icons.attachment_rounded, "attachment_rounded"),
    FlutterIconModel(Icons.attachment_sharp, "attachment_sharp"),
    FlutterIconModel(Icons.attractions, "attractions"),
    FlutterIconModel(Icons.attractions_outlined, "attractions_outlined"),
    FlutterIconModel(Icons.attractions_rounded, "attractions_rounded"),
    FlutterIconModel(Icons.attractions_sharp, "attractions_sharp"),
    FlutterIconModel(Icons.attribution, "attribution"),
    FlutterIconModel(Icons.attribution_outlined, "attribution_outlined"),
    FlutterIconModel(Icons.attribution_rounded, "attribution_rounded"),
    FlutterIconModel(Icons.attribution_sharp, "attribution_sharp"),
    FlutterIconModel(Icons.audio_file, "audio_file"),
    FlutterIconModel(Icons.audio_file_outlined, "audio_file_outlined"),
    FlutterIconModel(Icons.audio_file_rounded, "audio_file_rounded"),
    FlutterIconModel(Icons.audio_file_sharp, "audio_file_sharp"),
    FlutterIconModel(Icons.audiotrack, "audiotrack"),
    FlutterIconModel(Icons.audiotrack_outlined, "audiotrack_outlined"),
    FlutterIconModel(Icons.audiotrack_rounded, "audiotrack_rounded"),
    FlutterIconModel(Icons.audiotrack_sharp, "audiotrack_sharp"),
    FlutterIconModel(Icons.auto_awesome, "auto_awesome"),
    FlutterIconModel(Icons.auto_awesome_mosaic, "auto_awesome_mosaic"),
    FlutterIconModel(
        Icons.auto_awesome_mosaic_outlined, "auto_awesome_mosaic_outlined"),
    FlutterIconModel(
        Icons.auto_awesome_mosaic_rounded, "auto_awesome_mosaic_rounded"),
    FlutterIconModel(
        Icons.auto_awesome_mosaic_sharp, "auto_awesome_mosaic_sharp"),
    FlutterIconModel(Icons.auto_awesome_motion, "auto_awesome_motion"),
    FlutterIconModel(
        Icons.auto_awesome_motion_outlined, "auto_awesome_motion_outlined"),
    FlutterIconModel(
        Icons.auto_awesome_motion_rounded, "auto_awesome_motion_rounded"),
    FlutterIconModel(
        Icons.auto_awesome_motion_sharp, "auto_awesome_motion_sharp"),
    FlutterIconModel(Icons.auto_awesome_outlined, "auto_awesome_outlined"),
    FlutterIconModel(Icons.auto_awesome_rounded, "auto_awesome_rounded"),
    FlutterIconModel(Icons.auto_awesome_sharp, "auto_awesome_sharp"),
    FlutterIconModel(Icons.auto_delete, "auto_delete"),
    FlutterIconModel(Icons.auto_delete_outlined, "auto_delete_outlined"),
    FlutterIconModel(Icons.auto_delete_rounded, "auto_delete_rounded"),
    FlutterIconModel(Icons.auto_delete_sharp, "auto_delete_sharp"),
    FlutterIconModel(Icons.auto_fix_high, "auto_fix_high"),
    FlutterIconModel(Icons.auto_fix_high_outlined, "auto_fix_high_outlined"),
    FlutterIconModel(Icons.auto_fix_high_rounded, "auto_fix_high_rounded"),
    FlutterIconModel(Icons.auto_fix_high_sharp, "auto_fix_high_sharp"),
    FlutterIconModel(Icons.auto_fix_normal, "auto_fix_normal"),
    FlutterIconModel(
        Icons.auto_fix_normal_outlined, "auto_fix_normal_outlined"),
    FlutterIconModel(Icons.auto_fix_normal_rounded, "auto_fix_normal_rounded"),
    FlutterIconModel(Icons.auto_fix_normal_sharp, "auto_fix_normal_sharp"),
    FlutterIconModel(Icons.auto_fix_off, "auto_fix_off"),
    FlutterIconModel(Icons.auto_fix_off_outlined, "auto_fix_off_outlined"),
    FlutterIconModel(Icons.auto_fix_off_rounded, "auto_fix_off_rounded"),
    FlutterIconModel(Icons.auto_fix_off_sharp, "auto_fix_off_sharp"),
    FlutterIconModel(Icons.auto_graph, "auto_graph"),
    FlutterIconModel(Icons.auto_graph_outlined, "auto_graph_outlined"),
    FlutterIconModel(Icons.auto_graph_rounded, "auto_graph_rounded"),
    FlutterIconModel(Icons.auto_graph_sharp, "auto_graph_sharp"),
    FlutterIconModel(Icons.auto_mode, "auto_mode"),
    FlutterIconModel(Icons.auto_mode_outlined, "auto_mode_outlined"),
    FlutterIconModel(Icons.auto_mode_rounded, "auto_mode_rounded"),
    FlutterIconModel(Icons.auto_mode_sharp, "auto_mode_sharp"),
    FlutterIconModel(Icons.auto_stories, "auto_stories"),
    FlutterIconModel(Icons.auto_stories_outlined, "auto_stories_outlined"),
    FlutterIconModel(Icons.auto_stories_rounded, "auto_stories_rounded"),
    FlutterIconModel(Icons.auto_stories_sharp, "auto_stories_sharp"),
    FlutterIconModel(Icons.autofps_select, "autofps_select"),
    FlutterIconModel(Icons.autofps_select_outlined, "autofps_select_outlined"),
    FlutterIconModel(Icons.autofps_select_rounded, "autofps_select_rounded"),
    FlutterIconModel(Icons.autofps_select_sharp, "autofps_select_sharp"),
    FlutterIconModel(Icons.autorenew, "autorenew"),
    FlutterIconModel(Icons.autorenew_outlined, "autorenew_outlined"),
    FlutterIconModel(Icons.autorenew_rounded, "autorenew_rounded"),
    FlutterIconModel(Icons.autorenew_sharp, "autorenew_sharp"),
    FlutterIconModel(Icons.av_timer, "av_timer"),
    FlutterIconModel(Icons.av_timer_outlined, "av_timer_outlined"),
    FlutterIconModel(Icons.av_timer_rounded, "av_timer_rounded"),
    FlutterIconModel(Icons.av_timer_sharp, "av_timer_sharp"),
    FlutterIconModel(Icons.baby_changing_station, "baby_changing_station"),
    FlutterIconModel(
        Icons.baby_changing_station_outlined, "baby_changing_station_outlined"),
    FlutterIconModel(
        Icons.baby_changing_station_rounded, "baby_changing_station_rounded"),
    FlutterIconModel(
        Icons.baby_changing_station_sharp, "baby_changing_station_sharp"),
    FlutterIconModel(Icons.back_hand, "back_hand"),
    FlutterIconModel(Icons.back_hand_outlined, "back_hand_outlined"),
    FlutterIconModel(Icons.back_hand_rounded, "back_hand_rounded"),
    FlutterIconModel(Icons.back_hand_sharp, "back_hand_sharp"),
    FlutterIconModel(Icons.backpack, "backpack"),
    FlutterIconModel(Icons.backpack_outlined, "backpack_outlined"),
    FlutterIconModel(Icons.backpack_rounded, "backpack_rounded"),
    FlutterIconModel(Icons.backpack_sharp, "backpack_sharp"),
    FlutterIconModel(Icons.backspace, "backspace"),
    FlutterIconModel(Icons.backspace_outlined, "backspace_outlined"),
    FlutterIconModel(Icons.backspace_rounded, "backspace_rounded"),
    FlutterIconModel(Icons.backspace_sharp, "backspace_sharp"),
    FlutterIconModel(Icons.backup, "backup"),
    FlutterIconModel(Icons.backup_outlined, "backup_outlined"),
    FlutterIconModel(Icons.backup_rounded, "backup_rounded"),
    FlutterIconModel(Icons.backup_sharp, "backup_sharp"),
    FlutterIconModel(Icons.backup_table, "backup_table"),
    FlutterIconModel(Icons.backup_table_outlined, "backup_table_outlined"),
    FlutterIconModel(Icons.backup_table_rounded, "backup_table_rounded"),
    FlutterIconModel(Icons.backup_table_sharp, "backup_table_sharp"),
    FlutterIconModel(Icons.badge, "badge"),
    FlutterIconModel(Icons.badge_outlined, "badge_outlined"),
    FlutterIconModel(Icons.badge_rounded, "badge_rounded"),
    FlutterIconModel(Icons.badge_sharp, "badge_sharp"),
    FlutterIconModel(Icons.bakery_dining, "bakery_dining"),
    FlutterIconModel(Icons.bakery_dining_outlined, "bakery_dining_outlined"),
    FlutterIconModel(Icons.bakery_dining_rounded, "bakery_dining_rounded"),
    FlutterIconModel(Icons.bakery_dining_sharp, "bakery_dining_sharp"),
    FlutterIconModel(Icons.balance, "balance"),
    FlutterIconModel(Icons.balance_outlined, "balance_outlined"),
    FlutterIconModel(Icons.balance_rounded, "balance_rounded"),
    FlutterIconModel(Icons.balance_sharp, "balance_sharp"),
    FlutterIconModel(Icons.balcony, "balcony"),
    FlutterIconModel(Icons.balcony_outlined, "balcony_outlined"),
    FlutterIconModel(Icons.balcony_rounded, "balcony_rounded"),
    FlutterIconModel(Icons.balcony_sharp, "balcony_sharp"),
    FlutterIconModel(Icons.ballot, "ballot"),
    FlutterIconModel(Icons.ballot_outlined, "ballot_outlined"),
    FlutterIconModel(Icons.ballot_rounded, "ballot_rounded"),
    FlutterIconModel(Icons.ballot_sharp, "ballot_sharp"),
    FlutterIconModel(Icons.bar_chart, "bar_chart"),
    FlutterIconModel(Icons.bar_chart_rounded, "bar_chart_rounded"),
    FlutterIconModel(Icons.bar_chart_outlined, "bar_chart_outlined"),
    FlutterIconModel(Icons.bar_chart_sharp, "bar_chart_sharp"),
    FlutterIconModel(Icons.batch_prediction, "batch_prediction"),
    FlutterIconModel(
        Icons.batch_prediction_outlined, "batch_prediction_outlined"),
    FlutterIconModel(
        Icons.batch_prediction_rounded, "batch_prediction_rounded"),
    FlutterIconModel(Icons.batch_prediction_sharp, "batch_prediction_sharp"),
    FlutterIconModel(Icons.bathroom, "bathroom"),
    FlutterIconModel(Icons.bathroom_outlined, "bathroom_outlined"),
    FlutterIconModel(Icons.bathroom_rounded, "bathroom_rounded"),
    FlutterIconModel(Icons.bathroom_sharp, "bathroom_sharp"),
    FlutterIconModel(Icons.bathtub, "bathtub"),
    FlutterIconModel(Icons.bathtub_outlined, "bathtub_outlined"),
    FlutterIconModel(Icons.bathtub_rounded, "bathtub_rounded"),
    FlutterIconModel(Icons.bathtub_sharp, "bathtub_sharp"),
    FlutterIconModel(Icons.battery_0_bar, "battery_0_bar"),
    FlutterIconModel(Icons.battery_0_bar_outlined, "battery_0_bar_outlined"),
    FlutterIconModel(Icons.battery_0_bar_rounded, "battery_0_bar_rounded"),
    FlutterIconModel(Icons.battery_0_bar_sharp, "battery_0_bar_sharp"),
    FlutterIconModel(Icons.battery_1_bar, "battery_1_bar"),
    FlutterIconModel(Icons.battery_1_bar_outlined, "battery_1_bar_outlined"),
    FlutterIconModel(Icons.battery_1_bar_rounded, "battery_1_bar_rounded"),
    FlutterIconModel(Icons.battery_1_bar_sharp, "battery_1_bar_sharp"),
    FlutterIconModel(Icons.battery_2_bar, "battery_2_bar"),
    FlutterIconModel(Icons.battery_2_bar_outlined, "battery_2_bar_outlined"),
    FlutterIconModel(Icons.battery_2_bar_rounded, "battery_2_bar_rounded"),
    FlutterIconModel(Icons.battery_2_bar_sharp, "battery_2_bar_sharp"),
    FlutterIconModel(Icons.battery_3_bar, "battery_3_bar"),
    FlutterIconModel(Icons.battery_3_bar_outlined, "battery_3_bar_outlined"),
    FlutterIconModel(Icons.battery_3_bar_rounded, "battery_3_bar_rounded"),
    FlutterIconModel(Icons.battery_3_bar_sharp, "battery_3_bar_sharp"),
    FlutterIconModel(Icons.battery_4_bar, "battery_4_bar"),
    FlutterIconModel(Icons.battery_4_bar_outlined, "battery_4_bar_outlined"),
    FlutterIconModel(Icons.battery_4_bar_rounded, "battery_4_bar_rounded"),
    FlutterIconModel(Icons.battery_4_bar_sharp, "battery_4_bar_sharp"),
    FlutterIconModel(Icons.battery_5_bar, "battery_5_bar"),
    FlutterIconModel(Icons.battery_5_bar_outlined, "battery_5_bar_outlined"),
    FlutterIconModel(Icons.battery_5_bar_rounded, "battery_5_bar_rounded"),
    FlutterIconModel(Icons.battery_5_bar_sharp, "battery_5_bar_sharp"),
    FlutterIconModel(Icons.battery_6_bar, "battery_6_bar"),
    FlutterIconModel(Icons.battery_6_bar_outlined, "battery_6_bar_outlined"),
    FlutterIconModel(Icons.battery_6_bar_rounded, "battery_6_bar_rounded"),
    FlutterIconModel(Icons.battery_6_bar_sharp, "battery_6_bar_sharp"),
    FlutterIconModel(Icons.battery_alert, "battery_alert"),
    FlutterIconModel(Icons.battery_alert_outlined, "battery_alert_outlined"),
    FlutterIconModel(Icons.battery_alert_rounded, "battery_alert_rounded"),
    FlutterIconModel(Icons.battery_alert_sharp, "battery_alert_sharp"),
    FlutterIconModel(Icons.battery_charging_full, "battery_charging_full"),
    FlutterIconModel(
        Icons.battery_charging_full_outlined, "battery_charging_full_outlined"),
    FlutterIconModel(
        Icons.battery_charging_full_rounded, "battery_charging_full_rounded"),
    FlutterIconModel(
        Icons.battery_charging_full_sharp, "battery_charging_full_sharp"),
    FlutterIconModel(Icons.battery_full, "battery_full"),
    FlutterIconModel(Icons.battery_full_outlined, "battery_full_outlined"),
    FlutterIconModel(Icons.battery_full_rounded, "battery_full_rounded"),
    FlutterIconModel(Icons.battery_full_sharp, "battery_full_sharp"),
    FlutterIconModel(Icons.battery_saver, "battery_saver"),
    FlutterIconModel(Icons.battery_saver_outlined, "battery_saver_outlined"),
    FlutterIconModel(Icons.battery_saver_rounded, "battery_saver_rounded"),
    FlutterIconModel(Icons.battery_saver_sharp, "battery_saver_sharp"),
    FlutterIconModel(Icons.battery_std, "battery_std"),
    FlutterIconModel(Icons.battery_std_outlined, "battery_std_outlined"),
    FlutterIconModel(Icons.battery_std_rounded, "battery_std_rounded"),
    FlutterIconModel(Icons.battery_std_sharp, "battery_std_sharp"),
    FlutterIconModel(Icons.battery_unknown, "battery_unknown"),
    FlutterIconModel(
        Icons.battery_unknown_outlined, "battery_unknown_outlined"),
    FlutterIconModel(Icons.battery_unknown_rounded, "battery_unknown_rounded"),
    FlutterIconModel(Icons.battery_unknown_sharp, "battery_unknown_sharp"),
    FlutterIconModel(Icons.beach_access, "beach_access"),
    FlutterIconModel(Icons.beach_access_outlined, "beach_access_outlined"),
    FlutterIconModel(Icons.beach_access_rounded, "beach_access_rounded"),
    FlutterIconModel(Icons.beach_access_sharp, "beach_access_sharp"),
    FlutterIconModel(Icons.bed, "bed"),
    FlutterIconModel(Icons.bed_outlined, "bed_outlined"),
    FlutterIconModel(Icons.bed_rounded, "bed_rounded"),
    FlutterIconModel(Icons.bed_sharp, "bed_sharp"),
    FlutterIconModel(Icons.bedroom_baby, "bedroom_baby"),
    FlutterIconModel(Icons.bedroom_baby_outlined, "bedroom_baby_outlined"),
    FlutterIconModel(Icons.bedroom_baby_rounded, "bedroom_baby_rounded"),
    FlutterIconModel(Icons.bedroom_baby_sharp, "bedroom_baby_sharp"),
    FlutterIconModel(Icons.bedroom_child, "bedroom_child"),
    FlutterIconModel(Icons.bedroom_child_outlined, "bedroom_child_outlined"),
    FlutterIconModel(Icons.bedroom_child_rounded, "bedroom_child_rounded"),
    FlutterIconModel(Icons.bedroom_child_sharp, "bedroom_child_sharp"),
    FlutterIconModel(Icons.bedroom_parent, "bedroom_parent"),
    FlutterIconModel(Icons.bedroom_parent_outlined, "bedroom_parent_outlined"),
    FlutterIconModel(Icons.bedroom_parent_rounded, "bedroom_parent_rounded"),
    FlutterIconModel(Icons.bedroom_parent_sharp, "bedroom_parent_sharp"),
    FlutterIconModel(Icons.bedtime, "bedtime"),
    FlutterIconModel(Icons.bedtime_off, "bedtime_off"),
    FlutterIconModel(Icons.bedtime_off_outlined, "bedtime_off_outlined"),
    FlutterIconModel(Icons.bedtime_off_rounded, "bedtime_off_rounded"),
    FlutterIconModel(Icons.bedtime_off_sharp, "bedtime_off_sharp"),
    FlutterIconModel(Icons.bedtime_outlined, "bedtime_outlined"),
    FlutterIconModel(Icons.bedtime_rounded, "bedtime_rounded"),
    FlutterIconModel(Icons.bedtime_sharp, "bedtime_sharp"),
    FlutterIconModel(Icons.beenhere, "beenhere"),
    FlutterIconModel(Icons.beenhere_outlined, "beenhere_outlined"),
    FlutterIconModel(Icons.beenhere_rounded, "beenhere_rounded"),
    FlutterIconModel(Icons.beenhere_sharp, "beenhere_sharp"),
    FlutterIconModel(Icons.bento, "bento"),
    FlutterIconModel(Icons.bento_outlined, "bento_outlined"),
    FlutterIconModel(Icons.bento_rounded, "bento_rounded"),
    FlutterIconModel(Icons.bento_sharp, "bento_sharp"),
    FlutterIconModel(Icons.bike_scooter, "bike_scooter"),
    FlutterIconModel(Icons.bike_scooter_outlined, "bike_scooter_outlined"),
    FlutterIconModel(Icons.bike_scooter_rounded, "bike_scooter_rounded"),
    FlutterIconModel(Icons.bike_scooter_sharp, "bike_scooter_sharp"),
    FlutterIconModel(Icons.biotech, "biotech"),
    FlutterIconModel(Icons.biotech_outlined, "biotech_outlined"),
    FlutterIconModel(Icons.biotech_rounded, "biotech_rounded"),
    FlutterIconModel(Icons.biotech_sharp, "biotech_sharp"),
    FlutterIconModel(Icons.blender, "blender"),
    FlutterIconModel(Icons.blender_outlined, "blender_outlined"),
    FlutterIconModel(Icons.blender_rounded, "blender_rounded"),
    FlutterIconModel(Icons.blender_sharp, "blender_sharp"),
    FlutterIconModel(Icons.blinds, "blinds"),
    FlutterIconModel(Icons.blinds_closed, "blinds_closed"),
    FlutterIconModel(Icons.blinds_closed_outlined, "blinds_closed_outlined"),
    FlutterIconModel(Icons.blinds_closed_rounded, "blinds_closed_rounded"),
    FlutterIconModel(Icons.blinds_closed_sharp, "blinds_closed_sharp"),
    FlutterIconModel(Icons.blinds_outlined, "blinds_outlined"),
    FlutterIconModel(Icons.blinds_rounded, "blinds_rounded"),
    FlutterIconModel(Icons.blinds_sharp, "blinds_sharp"),
    FlutterIconModel(Icons.block, "block"),
    FlutterIconModel(Icons.block_flipped, "block_flipped"),
    FlutterIconModel(Icons.block_outlined, "block_outlined"),
    FlutterIconModel(Icons.block_rounded, "block_rounded"),
    FlutterIconModel(Icons.block_sharp, "block_sharp"),
    FlutterIconModel(Icons.bloodtype, "bloodtype"),
    FlutterIconModel(Icons.bloodtype_outlined, "bloodtype_outlined"),
    FlutterIconModel(Icons.bloodtype_rounded, "bloodtype_rounded"),
    FlutterIconModel(Icons.bloodtype_sharp, "bloodtype_sharp"),
    FlutterIconModel(Icons.bluetooth, "bluetooth"),
    FlutterIconModel(Icons.bluetooth_audio, "bluetooth_audio"),
    FlutterIconModel(
        Icons.bluetooth_audio_outlined, "bluetooth_audio_outlined"),
    FlutterIconModel(Icons.bluetooth_audio_rounded, "bluetooth_audio_rounded"),
    FlutterIconModel(Icons.bluetooth_audio_sharp, "bluetooth_audio_sharp"),
    FlutterIconModel(Icons.bluetooth_connected, "bluetooth_connected"),
    FlutterIconModel(
        Icons.bluetooth_connected_rounded, "bluetooth_connected_rounded"),
    FlutterIconModel(
        Icons.bluetooth_connected_outlined, "bluetooth_connected_outlined"),
    FlutterIconModel(
        Icons.bluetooth_connected_sharp, "bluetooth_connected_sharp"),
    FlutterIconModel(Icons.bluetooth_disabled, "bluetooth_disabled"),
    FlutterIconModel(
        Icons.bluetooth_disabled_outlined, "bluetooth_disabled_outlined"),
    FlutterIconModel(
        Icons.bluetooth_disabled_rounded, "bluetooth_disabled_rounded"),
    FlutterIconModel(
        Icons.bluetooth_disabled_sharp, "bluetooth_disabled_sharp"),
    FlutterIconModel(Icons.bluetooth_drive, "bluetooth_drive"),
    FlutterIconModel(
        Icons.bluetooth_drive_outlined, "bluetooth_drive_outlined"),
    FlutterIconModel(Icons.bluetooth_drive_rounded, "bluetooth_drive_rounded"),
    FlutterIconModel(Icons.bluetooth_drive_sharp, "bluetooth_drive_sharp"),
    FlutterIconModel(Icons.bluetooth_outlined, "bluetooth_outlined"),
    FlutterIconModel(Icons.bluetooth_outlined, "bluetooth_outlined"),
  ];
}
